import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import  { useRouter } from 'next/router'
import db from '../../utils/db'
import { useState } from 'react'
import { useEffect } from 'react'
import useSWR from 'swr'
import fetcher from '../../utils/fetcher'
import Product from '../../models/Product'

const inter = Inter({ subsets: ['latin'] })


export default function Test({products}) {
  console.log(products)

  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
    {products && products.map((prod) => {
      return (
        <h3>{prod.Name}</h3>
      )
    })}

      </div>
    </>
  )
}

export async function getServerSideProps(context) {

  const categoryName = context.query.category

  await db.connect();
  const products = await Product.find({Category: categoryName}).lean();
  return {
    props: {
      products: products.map(db.convertDocToObj),
    },
  };
}