export const ProductList = [
  {
    Name: "Ducky One 2 Mecha ",
    Brand: "Ducky",
    Price: 1690,
    Img1: "duckyone2mecha1.webp",
    Img2: "duckyone2mecha2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Ducky One 2 Tuxedo",
    Brand: "Ducky",
    Price: 1290,
    Img1: "duckyone2tuxedo1.webp",
    Img2: "duckyone2tuxedo2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Ducky One 3 Daybreak SF",
    Brand: "Ducky",
    Price: 1849,
    Img1: "duckyone3daybreaksf1.webp",
    Img2: "duckyone3daybreaksf2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Ducky One 3 Matcha",
    Brand: "Ducky",
    Price: 1490,
    Img1: "duckyone3matcha1.webp",
    Img2: "duckyone3matcha2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Ducky MIYA Pro Sakura TKL",
    Brand: "Ducky",
    Price: 1790,
    Img1: "DuckyMIYAProSakuraTKL1.webp",
    Img2: "DuckyMIYAProSakuraTKL2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Keychron K2 V2",
    Brand: "Keychron",
    Price: "1190",
    Img1: "KeychronK2V21.webp",
    Img2: "KeychronK2V22.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Keychron K6",
    Brand: "Keychron",
    Price: 1190,
    Img1: "KeychronK61.webp",
    Img2: "KeychronK62.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Keychron K8 Pro",
    Brand: "Keychron",
    Price: 1189,
    Img1: "KeychronK81.webp",
    Img2: "keychronK82.webp",
    Category: "Keyboards.webp",
    Qty: 100,
  },
  {
    Name: "Keychron K3 Ultra Slim V2",
    Brand: "Keychron",
    Price: 1249,
    Img1: "KeychronK3UltraslimV21.webp",
    Img2: "KeychronK3UltraslimV22.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Keychron K4 v2 ",
    Brand: "Keychron",
    Price: 1249,
    Img1: "Keychronk4v21.webp",
    Img2: "keychronk4v22.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Varmilo VA69",
    Brand: "Varmilo",
    Price: 1149,
    Img1: "varmilova691.webp",
    Img2: "varmilova692.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Varmilo VEA88 Sea Melody TKL",
    Brand: "Varmilo",
    Price: 1699,
    Img1: "vea88seamelody1.webp",
    Img2: "vea88seamelody2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Varmilo VEA109 Panda R2 V2",
    Brand: "Varmilo",
    Price: 1699,
    Img1: "VEA109PandaR2V21.webp",
    Img2: "VEA109PandaR2V22.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Varmilo VEA 109 Yakumo V2",
    Brand: "Varmilo",
    Price: 1999,
    Img1: "varmilovea109yakumov21.webp",
    Img2: "varmilovea109yakumov22.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Varmilo VEA 88",
    Brand: "Varmilo",
    Price: 1399,
    Img1: "varmilovea881.webp",
    Img2: "varmilovea882.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Yunzii CoolKiller CK 75 Mint Green",
    Brand: "Yunzii",
    Price: 1989,
    Img1: "yunziicoolkillerck751.webp",
    Img2: "yunziicoolkillerck752.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Yunzii KC84S Milk Honey",
    Brand: "Yunzii",
    Price: 1100,
    Img1: "yunziikc84s1.webp",
    Img2: "yunziikc84s2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Yunzii Keynovo IF98",
    Brand: "Yunzii",
    Price: 1359,
    Img1: "yunziikeynovoif98pro1.webp",
    Img2: "yunziikeynovoif98pro2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Yunzii Macaron ",
    Brand: "Yunzii",
    Price: 999,
    Img1: "yunziimacaron1.webp",
    Img2: "yunziimacaron2.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Yunzii VN66",
    Brand: "Yunzii",
    Price: 940,
    Img1: "yunziivn661.webp",
    Img2: "yunziivn662.webp",
    Category: "Keyboards",
    Qty: 100,
    Switches: ["mx red", "mx blue", "mx black", "mx brown"]
  },
  {
    Name: "Cooler Master Thunderstom Purple",
    Price: 249,
    Img1: "cmthunderstormpurple1.webp",
    Img2: "cmthunderstormpurple2.webp",
    Brand: "Cables",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Glorious Coil Cable Phantom Black",
    Price: 679,
    Img1: "gloriouscoilblack1.webp",
    Img2: "gloriouscoilblack2.webp",
    Brand: "Cables",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Keychron Custom Coiled Aviator Cable Black",
    Price: 249,
    Img1: "keychroncoilblack1.webp",
    Img2: "keychroncoilblack2.webp",
    Brand: "Cables",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "MaxMount Premium Aviator Coiled Cable Gray",
    Price: 399,
    Img1: "maxmountpremiumaviatorgray1.webp",
    Img2: "maxmountpremiumaviatorgray2.webp",
    Brand: "Cables",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "MaxMount Premium Aviator Coiled Cable Purple",
    Price: 399,
    Img1: "premiumaviatorpurple1.webp",
    Img2: "premiumaviatorpurple2.webp",
    Brand: "Cables",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "CableMod Pro Coiled Cable Blue",
    Price: 569,
    Img1: "procoiledblue1.webp",
    Img2: "procoiledblue2.webp",
    Brand: "Cables",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "CableMod Pro Coiled Cable Green",
    Price: 569,
    Img1: "procoiledgreen1.webp",
    Img2: "procoiledgreen2.webp",
    Brand: "Cables",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Varmilo Mulan Beijing Opera",
    Price: 249,
    Img1: "MulanBeijingOpera.webp",
    Brand: "Desktop Pads",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Varmilo Daisy",
    Price: 249,
    Img1: "varmilodaisy.webp",
    Brand: "Desktop Pads",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Varmilo Forest Fairy ",
    Price: 249,
    Img1: "varmiloforestfairy.webp",
    Brand: "Desktop Pads",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Varmilo MousePad XL",
    Price: 249,
    Img1: "varmilomousepadxl1.webp",
    Brand: "Desktop Pads",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "X Gamer Cyber Bot XXL",
    Price: 349,
    Img1: "xgamercyberbot.webp",
    Brand: "Desktop Pads",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "X Gamer Ginger Queen XXL",
    Price: 399,
    Img1: "xgamergingerqueen.webp",
    Brand: "Desktop Pads",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "X Gamer Persian Ruby XXL ",
    Price: 399,
    Img1: "xgamerpersianruby.webp",
    Brand: "Desktop Pads",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Ducky Wrist Rest TKL",
    Price: 349,
    Img1: "duckywristrestTKL.webp",
    Brand: "Wrist Rest",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Glorious Gaming Race Stealth TKL",
    Price: 279,
    Img1: "gloriousracestealthTKL.webp",
    Brand: "Wrist Rest",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "KBDfans Alopow Resin wrist rest  Galaxy Purple",
    Price: 329,
    Img1: "kbdfansalopowresingalaxypurple.webp",
    Brand: "Wrist Rest",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Keychron K2/K6 Walnut Wood",
    Price: 290,
    Img1: "keychronK2K6WalnutWood.webp",
    Brand: "Wrist Rest",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Keychron K8 Walnut Wood",
    Price: 290,
    Img1: "keychronk8walnutwood.webp",
    Brand: "Wrist Rest",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "MaxMount Wrist Rest TKL",
    Price: 149,
    Img1: "maxmountwristrestTKL.webp",
    Brand: "Wrist Rest",
    Category: "Accessories",
    Qty: 100,
  },
  {
    Name: "Xtrfy WR2 Wrist Rest Bamboo",
    Price: 279,
    Img1: "xtrfywr2bamboo.webp",
    Brand: "Wrist Rest",
    Category: "Accessories",
    Qty: 100,
  },
];
