import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import  { useRouter } from 'next/router'
import db from '../utils/db'
import { useState } from 'react'
import { useEffect } from 'react'
import useSWR from 'swr'
import fetcher from '../utils/fetcher'
import Product from '../models/Product'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })


export default function Test({products}) {
    
    const router = useRouter()
    console.log(products)

    useEffect(() => {
        if (products.length == 0) {
          router.back()
        }
      }, [])

  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {products && products.map((prod) => {
      return (
        <div>
          <h3>{prod.Name}</h3>
          <Image src={`/assets/${prod.Img1}`} width={'300'} height={'300'} alt={prod.name} />
        </div>
        
      )
    })}
    </>
  )
}

export async function getServerSideProps(context) {

  const brandName = context.query.brand

  await db.connect();
  const products = await Product.find({Brand: brandName}).lean();
  return {
    props: {
      products: products.map(db.convertDocToObj),
    },
  };
}